apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-ugaclffp
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-ugaclffp:5160f25024710270094bc0184c74de8864e0f642@sha256:e26dfa1f5fd2fbc94252c93da823021e4e1af91aad2071e8327eef372be2f2f4
          name: container-image
